"""
Variables to help with plotting
"""

limits_dict = {"TauTracks.dEta": [-0.5, 0.5],
              "TauTracks.dPhi": [-0.5, 0.5],
              "TauTracks.nInnermostPixelHits": [0, 20],
              "TauTracks.nPixelHits": [0, 20],
              "TauTracks.nSCTHits": [0, 20],
              "TauTracks.pt": [15000.0, 1.5e6],
              #"TauTracks.dphiECal": [],
              #"TauTracks.detaECal": [],
              #"TauTracks.jetpt": [],
              "TauTracks.d0TJVA": [-4, 4],
              "TauTracks.d0SigTJVA": [-4, 4],
              "TauTracks.z0sinthetaTJVA": [-50, 50],
              "TauTracks.z0sinthetaSigTJVA": [-75, 75],

              "ConvTrack.dphiECal": [-0.5, 0.5],
              "ConvTrack.dphi": [-0.5, 0.5],
              "ConvTrack.detaECal": [-0.5, 0.5],
              "ConvTrack.deta": [-0.5, 0.5],
              "ConvTrack.pt": [15000.0, 1.5e6],
              "ConvTrack.jetpt": [15000.0, 1.5e6],
              "ConvTrack.d0TJVA": [-4, 4],
              "ConvTrack.d0SigTJVA": [-4, 4],
              "ConvTrack.z0sinthetaTJVA": [-75, 75],
              "ConvTrack.z0sinthetaSigTJVA": [-50, 50],

              "ShotPFO.dphiECal": [-0.5, 0.5],
              "ShotPFO.dphi": [-0.5, 0.5],
              "ShotPFO.detaECal": [-0.5, 0.5],
              "ShotPFO.deta": [-0.5, 0.5],
              "ShotPFO.pt": [15000.0, 1.5e6],
              "ShotPFO.jetpt": [15000.0, 1.5e6],

              "NeutralPFO.dphiECal": [-0.5, 0.5],
              "NeutralPFO.dphi": [-0.5, 0.5],
              "NeutralPFO.detaECal": [-0.5, 0.5],
              "NeutralPFO.deta": [-0.5, 0.5],
              "NeutralPFO.pt": [15000.0, 100000.0],
              "NeutralPFO.jetpt": [15000.0, 100000.0],
              "NeutralPFO.FIRST_ETA": [-3.2, 3.2],
              "NeutralPFO.SECOND_R": [0, 40e3],
              "NeutralPFO.DELTA_THETA": [0, 1],
              "NeutralPFO.CENTER_LAMBDA": [0, 1000],
              "NeutralPFO.LONGITUDINAL": [0, 1],
              "NeutralPFO.SECOND_ENG_DENS": [0, 1e-5],
              "NeutralPFO.ENG_FRAC_CORE": [0, 1],
              "NeutralPFO.NPosECells_EM1": [0, 100],
              "NeutralPFO.NPosECells_EM2": [0, 100],
              "NeutralPFO.energy_EM1": [15000.0, 100000.0],
              "NeutralPFO.energy_EM2": [15000.0, 100000.0],
              "NeutralPFO.EM1CoreFrac": [0, 1],
              "NeutralPFO.firstEtaWRTClusterPosition_EM1": [-0.05, 0.05],
              "NeutralPFO.firstEtaWRTClusterPosition_EM2": [-0.05, 0.05],
              "NeutralPFO.secondEtaWRTClusterPosition_EM1": [0, 0.001],
              "NeutralPFO.secondEtaWRTClusterPosition_EM2": [0, 0.001],

              "TauJets.centFrac": [0, 1],
              "TauJets.etOverPtLeadTrk": [0, 5],
              "TauJets.dRmax": [0, 0.3],
              "TauJets.SumPtTrkFrac": [0, 1],
              "TauJets.ptRatioEflowApprox": [-2, 2],
              "TauJets.mEflowApprox": [15000.0, 100000.0],
              "TauJets.ptJetSeed": [15000.0, 100000.0],
              "TauJets.etaJetSeed": [-3.2 , 3.2],
              "TauJets.phiJetSeed": [-3.2, 3.2],
            }