"""
List of input variables from MxAODs
TODO: Make this a yaml config file (Bad practice to use a .py file for configs)
"""
variables_dictionary = {"TauTracks": [

                                      "TauTracks.dEta",
                                      "TauTracks.dPhi",
                                      "TauTracks.nInnermostPixelHits",
                                      "TauTracks.nPixelHits",
                                      "TauTracks.nSCTHits",
                                      # "TauTracks.chargedScoreRNN",
                                      # "TauTracks.isolationScoreRNN",
                                      # "TauTracks.conversionScoreRNN",
                                      # "TauTracks.fakeScoreRNN",

                                      "TauTracks.pt",
                                      #"TauTracks.dphiECal",
                                      #"TauTracks.detaECal",
                                      #"TauTracks.jetpt",
                                      "TauTracks.d0TJVA",
                                      "TauTracks.d0SigTJVA",
                                      "TauTracks.z0sinthetaTJVA",
                                      "TauTracks.z0sinthetaSigTJVA"

                                      ],

                        "ConvTrack": ["ConvTrack.dphiECal",
                                      "ConvTrack.dphi",
                                      "ConvTrack.detaECal",
                                      "ConvTrack.deta",
                                      "ConvTrack.pt",
                                      "ConvTrack.jetpt",
                                      "ConvTrack.d0TJVA",
                                      "ConvTrack.d0SigTJVA",
                                      "ConvTrack.z0sinthetaTJVA",
                                      "ConvTrack.z0sinthetaSigTJVA"],

                        "ShotPFO": ["ShotPFO.dphiECal",
                                    "ShotPFO.dphi",
                                    "ShotPFO.detaECal",
                                    "ShotPFO.deta",
                                    "ShotPFO.pt",
                                    "ShotPFO.jetpt"],

                        "NeutralPFO": ["NeutralPFO.dphiECal",
                                       "NeutralPFO.dphi",
                                       "NeutralPFO.detaECal",
                                       "NeutralPFO.deta",
                                       "NeutralPFO.pt",
                                       "NeutralPFO.jetpt",
                                       "NeutralPFO.FIRST_ETA",
                                       "NeutralPFO.SECOND_R",
                                       "NeutralPFO.DELTA_THETA",
                                       "NeutralPFO.CENTER_LAMBDA",
                                       "NeutralPFO.LONGITUDINAL",
                                       "NeutralPFO.SECOND_ENG_DENS",
                                       "NeutralPFO.ENG_FRAC_CORE",
                                       "NeutralPFO.NPosECells_EM1",
                                       "NeutralPFO.NPosECells_EM2",
                                       "NeutralPFO.energy_EM1",
                                       "NeutralPFO.energy_EM2",
                                       "NeutralPFO.EM1CoreFrac",
                                       "NeutralPFO.firstEtaWRTClusterPosition_EM1",
                                       "NeutralPFO.firstEtaWRTClusterPosition_EM2",
                                       "NeutralPFO.secondEtaWRTClusterPosition_EM1",
                                       "NeutralPFO.secondEtaWRTClusterPosition_EM2"],

                        "TauJets": ["TauJets.centFrac",
                                    "TauJets.etOverPtLeadTrk",
                                    "TauJets.dRmax",
                                    "TauJets.SumPtTrkFrac",
                                    "TauJets.ptRatioEflowApprox",
                                    "TauJets.ptIntermediateAxis",
                                    "TauJets.ptJetSeed",
                                    "TauJets.etaJetSeed",
                                    "TauJets.phiJetSeed",
                                    ],

                        "DecayMode": ["TauJets.truthDecayMode"],
                        "Prong": ["TauJets.truthProng"],
                        "Weight": ["TauJets.jet_pt"]}#"TauJets.mcEventWeight"


variables_and_range_dict = {"TauTracks.dEta" : [-5, 5],
                            "TauTracks.dPhi" : [],
                            "TauTracks.nInnermostPixelHits" : [],
                            "TauTracks.nPixelHits" : [],
                            "TauTracks.nSCTHits" : [],
                            "TauTracks.pt" : [],
                            "TauTracks.d0TJVA" : [],
                            "TauTracks.d0SigTJVA" : [],
                            "TauTracks.z0sinthetaTJVA" : [],
                            "TauTracks.z0sinthetaSigTJVA" : [],
                            "ConvTrack.dphiECal" : [],
                            "ConvTrack.dphi" : [],
                            "ConvTrack.detaECal" : [],
                            "ConvTrack.deta" : [],
                            "ConvTrack.pt" : [],
                            "ConvTrack.jetpt" : [],
                            "ConvTrack.d0TJVA" : [],
                            "ConvTrack.d0SigTJVA" : [],
                            "ConvTrack.z0sinthetaTJVA" : [],
                            "ConvTrack.z0sinthetaSigTJVA" : [],
                            "ShotPFO.dphiECal" : [],
                             "ShotPFO.dphi" : [],
                             "ShotPFO.detaECal" : [],
                             "ShotPFO.deta" : [],
                             "ShotPFO.pt" : [],
                             "ShotPFO.jetpt" : [],
                            "NeutralPFO.dphiECal" : [],
                            "NeutralPFO.dphi" : [],
                            "NeutralPFO.detaECal" : [],
                            "NeutralPFO.deta" : [],
                            "NeutralPFO.pt" : [],
                            "NeutralPFO.jetpt" : [],
                            "NeutralPFO.FIRST_ETA" : [],
                            "NeutralPFO.SECOND_R" : [],
                            "NeutralPFO.DELTA_THETA" : [],
                            "NeutralPFO.CENTER_LAMBDA" : [],
                            "NeutralPFO.LONGITUDINAL" : [],
                            "NeutralPFO.SECOND_ENG_DENS" : [],
                            "NeutralPFO.ENG_FRAC_CORE" : [],
                            "NeutralPFO.NPosECells_EM1" : [],
                            "NeutralPFO.NPosECells_EM2" : [],
                            "NeutralPFO.energy_EM1" : [],
                            "NeutralPFO.energy_EM2" : [],
                            "NeutralPFO.EM1CoreFrac" : [],
                            "NeutralPFO.firstEtaWRTClusterPosition_EM1" : [],
                            "NeutralPFO.firstEtaWRTClusterPosition_EM2" : [],
                            "NeutralPFO.secondEtaWRTClusterPosition_EM1" : [],
                            "NeutralPFO.secondEtaWRTClusterPosition_EM2" : [],
                            "TauJets.centFrac" : [],
                            "TauJets.etOverPtLeadTrk" : [],
                            "TauJets.dRmax" : [],
                            "TauJets.SumPtTrkFrac" : [],
                            "TauJets.ptRatioEflowApprox" : [],
                            "TauJets.ptIntermediateAxis" : [],
                            "TauJets.ptJetSeed" : [],
                            "TauJets.etaJetSeed" : [],
                            "TauJets.phiJetSeed" : [],
                            }


variables_list = ["TauTracks.dEta",
                    "TauTracks.dPhi",
                    "TauTracks.nInnermostPixelHits",
                    "TauTracks.nPixelHits",
                    "TauTracks.nSCTHits",
                    "TauTracks.pt",
                    "TauTracks.d0TJVA",
                    "TauTracks.d0SigTJVA",
                    "TauTracks.z0sinthetaTJVA",
                    "TauTracks.z0sinthetaSigTJVA",
                    "ConvTrack.dphiECal",
                    "ConvTrack.dphi",
                    "ConvTrack.detaECal",
                    "ConvTrack.deta",
                    "ConvTrack.pt",
                    "ConvTrack.jetpt",
                    "ConvTrack.d0TJVA",
                    "ConvTrack.d0SigTJVA",
                    "ConvTrack.z0sinthetaTJVA",
                    "ConvTrack.z0sinthetaSigTJVA",
                    "ShotPFO.dphiECal",
                     "ShotPFO.dphi",
                     "ShotPFO.detaECal",
                     "ShotPFO.deta",
                     "ShotPFO.pt",
                     "ShotPFO.jetpt",
                    "NeutralPFO.dphiECal",
                    "NeutralPFO.dphi",
                    "NeutralPFO.detaECal",
                    "NeutralPFO.deta",
                    "NeutralPFO.pt",
                    "NeutralPFO.jetpt",
                    "NeutralPFO.FIRST_ETA",
                    "NeutralPFO.SECOND_R",
                    "NeutralPFO.DELTA_THETA",
                    "NeutralPFO.CENTER_LAMBDA",
                    "NeutralPFO.LONGITUDINAL",
                    "NeutralPFO.SECOND_ENG_DENS",
                    "NeutralPFO.ENG_FRAC_CORE",
                    "NeutralPFO.NPosECells_EM1",
                    "NeutralPFO.NPosECells_EM2",
                    "NeutralPFO.energy_EM1",
                    "NeutralPFO.energy_EM2",
                    "NeutralPFO.EM1CoreFrac",
                    "NeutralPFO.firstEtaWRTClusterPosition_EM1",
                    "NeutralPFO.firstEtaWRTClusterPosition_EM2",
                    "NeutralPFO.secondEtaWRTClusterPosition_EM1",
                    "NeutralPFO.secondEtaWRTClusterPosition_EM2",
                    "TauJets.centFrac",
                    "TauJets.etOverPtLeadTrk",
                    "TauJets.dRmax",
                    "TauJets.SumPtTrkFrac",
                    "TauJets.ptRatioEflowApprox",
                    "TauJets.ptIntermediateAxis",
                    "TauJets.ptJetSeed",
                    "TauJets.etaJetSeed",
                    "TauJets.phiJetSeed",]


